### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by limbusdev** [pserwylo/beat-game#55] opened 2021-02-19 21:44 UTC
Lags during the game make it almost impossible to jump at the right time. This might be related to the other bug regarding the assetmanager.

**Comment by pserwylo** [comment] 2021-02-20 00:38
Thanks for the feedback. You are absolutely correct that it will be related to the assetmanager issue. There is not a whole lot of physics per frame, so any performance issues I assume are graphical. Perhaps I'll tackle this as the next order of business. 

I'll close this as a duplicate of #34 (but rename it to make it more discoverable for others who hit poor performance).

In the meantime, would you mind sharing some specs of your phone here so I can get a feel for what type of devices experience poor performance?

**Closed by pserwylo** 2021-02-20 00:39 UTC
